### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by brunowego** [abe33/changelog-gen#9]
Have any way to see erros generated by `changelog-gen`? Minutos ago was working, but after generate a new version not working more.

**Comment by abe33** [comment]
I just pushed a version with proper trap for promise errors. I currently use Q, and promises sadly fails silently.

**Comment by brunowego** [comment]
The issue continue, I think is a bug with my repository. Another projects just works.

![bug](https://cloud.githubusercontent.com/assets/441774/10437544/38b55470-7104-11e5-8c71-7dea58e19bfa.gif)

Thanks @abe33.

**Comment by abe33** [comment]
Hmm, interesting, is it a public project? Maybe I'll be able to find the issue.

**Comment by brunowego** [comment]
@abe33 I send to your email the access for the project. Thanks!
